Repository ajitkumar1264/Algorithms, pull requests merged in 2022-09, with the labels that each got.

#1 hacktomber request
  practical1.py
Labels: documentation, Hacktoberfest

#3 hacktoberfest
  heapsort.java
Labels: Hacktoberfest

#5 hacktoberfest-2022
  Bike helmet tilt.dev
  Binary search
Labels: hacktoberfest

#6 hactoberfest-2022
  1.cpp
Labels: hacktoberfest

#7 Hacktoberfest - 2022
  merge.java
Labels: hacktoberfest

#8 hactoberfest- 2022
  bucketsort.java
Labels: hacktoberfest

#9 Add files via upload
  algorithms.java
Labels: hacktoberfest

#10 hacktoberfest-2022
  BubbleSort.java
Labels: hacktoberfest

#13 hacktoberfest-2022
  tree.cpp
Labels: hacktoberfest

#12 hacktoberfest-2022
  LinearSearch.java
Labels: hacktoberfest

#11 hacktoberfest-2022
  bubble_sort.java
Labels: hacktoberfest
